AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ETF Price Tracker

Parameters:
  LineChannelAccessToken:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /etf-price-tracker/line-channel-access-token
    Description: LINE Channel Access Token

  LineUserId:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /etf-price-tracker/line-user-id
    Description: LINE User ID
  S3Bucket:
    Type: String
    Description: S3 bucket name for chart image uploads

Globals:
  Function:
    Timeout: 180
    MemorySize: 256
    Runtime: python3.13

Resources:
  EtfPriceTrackerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: etf-price-tracker-function
      CodeUri: .
      Handler: src.handler.lambda_handler
      Description: ETF Price Tracker Lambda Function
      Environment:
        Variables:
          LINE_CHANNEL_ACCESS_TOKEN: !Ref LineChannelAccessToken
          LINE_USER_ID: !Ref LineUserId
          S3_BUCKET: !Ref S3Bucket

      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 0 ? * TUE-SAT *) # 日本時間の火曜日から土曜日の午前9時に実行(UTC AM0:00, NY夏時間AM1:00, NY冬時間AM2:00)
            Description: ETF Price Tracker Schedule Event
            Enabled: true
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub "arn:aws:s3:::${S3Bucket}/charts/*"

  EtfPriceTrackerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/etf-price-tracker-function"
      RetentionInDays: 14

Outputs:
  EtfPriceTrackerFunction:
    Description: ETF Price Tracker Lambda Function ARN
    Value: !GetAtt EtfPriceTrackerFunction.Arn

  EtfPriceTrackerFunctionIamRole:
    Description: Implicit IAM Role created for ETF Price Tracker function
    Value: !GetAtt EtfPriceTrackerFunctionRole.Arn
